### ISSUE TITLE
source code are not clear

### ISSUE THREAD

**Issue by clo-cry** [irtsa-dev/builtin-greyscript#1]
I see you put two different extended-function like **map.max** and **list.max** closely. It is hard to see totally what have added in of a certain builtin object. Hope you can fix it future.

**Comment by irtsa-dev** [comment]
> I see you put two different extended-function like **map.max** and **list.max** closely. It is hard to see totally what have added in of a certain builtin object. Hope you can fix it future.





In the source code, I put the **map.max** function and **list.max** function closer together because they are named the same but will behave slightly differently depending on if your using it for the **List** or if your using it for **Map**.


The [map.max](https://github.com/irtsa-dev/builtin-greyscript/wiki/New-Map-Functions#max) function will return the key that has the "longest" value in the given map.

The [list.max](https://github.com/irtsa-dev/builtin-greyscript/wiki/New-List-Functions#max) will return the "biggest" value in the given list.



Does this help?

**Comment by clo-cry** [comment]
> > I see you put two different extended-function like **map.max** and **list.max** closely. It is hard to see totally what have added in of a certain builtin object. Hope you can fix it future.
> 
> 
> 
> 
> 
> In the source code, I put the **map.max** function and **list.max** function closer together because they are named the same but will behave slightly differently depending on if your using it for the **List** or if your using it for **Map**.
> 
> 
> The [map.max](https://github.com/irtsa-dev/builtin-greyscript/wiki/New-Map-Functions#max) function will return the key that has the "longest" value in the given map.
> 
> The [list.max](https://github.com/irtsa-dev/builtin-greyscript/wiki/New-List-Functions#max) will return the "biggest" value in the given list.
> 
> 
> 
> Does this help?

 I see. I'll respect it if it is your coding style. But I perfer to put the methods belongs same object closer. It's not a big problem, you can just close this issure.
